const LAUNGE = {
  Polski: {
    icon: "🏬",
    label_zarzadzaj_firmami: "Zarządzaj firmami",
    welcome: "Witamy w panelu administracyjnym!",
    title_welcome: "Witamy",
    error_generic: "Wystąpił błąd.",
    success: "Sukces!",
    company_updated: "Firma została zaktualizowana pomyślnie.",
    company_saved_successfully: "Dane firmy zostały zapisane pomyślnie.",
    zapisz: "Zapisz",
    anuluj: "Anuluj",
    // menu okna zarzadaj firmami
    menu_label_zarzadzaj_firmami: "Przeglądaj firmy",
    menu_otworz: "Przegladaj firmy",
    menu_zapisz: "Dodaj nową firmę",
    menu_edytuj: "Edytuj firmę",
    menu_usun: "Usuń firmę",
    menu_label_zarzadzaj_pracownikami: "Zarządzaj pracownikami",
    menu_otworz_pracownikow: "Przeglądaj pracowników",
    // alerty i komunikaty
    alert: "Alert!",
    confirm_cancel_edit: "Anulować edycję?",
    confirm_delete_title: "Potwierdzenie usunięcia",
    confirm_delete_message: "Czy na pewno chcesz usunąć tę firmę?",
    brak_dostempu_do_modulu: "Brak dostępu do modułu. Skontaktuj się z administratorem.",
    usunieto_firme: "Firma została usunięta pomyślnie.",
    blad_przy_usuwaniu_firmy: "Wystąpił błąd podczas usuwania firmy.",
    // content dla przegladania firm w formie tabeli
    lista_firm: "Lista firm",
    name: "Nazwa firmy",
    type: "Typ firmy",
    active: "Aktywna",
    tax_id: "NIP",
    regon: "REGON",
    krs: "KRS",
    address: "Adres",
    city: "Miasto",
    postal_code: "Kod pocztowy",
    country: "Kraj",
    phone: "Telefon",
    email: "Email",
    website: "Strona www",
    validation_required: "Pole {field} jest wymagane.",
    validation_max_length: "Pole {field} może mieć maksymalnie {max} znaków.",
    validation_invalid_email: "Pole {field} musi zawierać poprawny adres e-mail.",
    validation_invalid_website: "Pole {field} musi zawierać poprawny adres URL (http:// lub https://).",
    created_at: "Data utworzenia",
    updated_at: "Data aktualizacji",
    company_details: "Szczegóły firmy",
    users_list: "Użytkownicy firmy",
    user_name: "Imię",
    user_email: "Email",
    user_role: "Rola",
    user_active: "Aktywny",
    user_lang: "Język",
    no_users: "Brak użytkowników powiązanych z tą firmą."
  },

  English: {
    icon: "🏬",
    label_zarzadzaj_firmami: "Manage companies",
    welcome: "Welcome to the admin panel!",
    title_welcome: "Welcome",
    error_generic: "An error occurred.",
    success: "Success!",
    company_updated: "Company updated successfully.",
    company_saved_successfully: "Company data saved successfully.",
    zapisz: "Save",
    anuluj: "Cancel",
    // menu okna zarzadzaj firmami
    menu_label_zarzadzaj_firmami: "Browse companies",
    menu_otworz: "Browse companies",
    menu_zapisz: "Add new company",
    menu_edytuj: "Edit company",
    menu_usun: "Delete company",
    menu_label_zarzadzaj_pracownikami: "Manage employees",
    menu_otworz_pracownikow: "Browse employees",
    // alerty i komunikaty
    alert: "Alert!",
    confirm_cancel_edit: "Cancel editing?",
    confirm_delete_title: "Delete confirmation",
    confirm_delete_message: "Are you sure you want to delete this company?",
    brak_dostempu_do_modulu: "No access to the module. Please contact the administrator.",
    usunieto_firme: "Company deleted successfully.",
    blad_przy_usuwaniu_firmy: "An error occurred while deleting the company.",
    // content dla przegladania firm w formie tabeli
    lista_firm: "Company list",
    name: "Company Name",
    type: "Company Type",
    active: "Active",
    tax_id: "Tax ID",
    regon: "REGON",
    krs: "KRS",
    address: "Address",
    city: "City",
    postal_code: "Postal Code",
    country: "Country",
    phone: "Phone",
    email: "Email",
    website: "Website",
    validation_required: "The {field} field is required.",
    validation_max_length: "The {field} field may contain at most {max} characters.",
    validation_invalid_email: "The {field} field must contain a valid email address.",
    validation_invalid_website: "The {field} field must contain a valid URL (http:// or https://).",
    created_at: "Created At",
    updated_at: "Updated At",
    company_details: "Company details",
    users_list: "Company users",
    user_name: "Name",
    user_email: "Email",
    user_role: "Role",
    user_active: "Active",
    user_lang: "Language",
    no_users: "No users found for this company."
  },

  Svenska: {
    icon: "🏬",
    label_zarzadzaj_firmami: "Hantera företag",
    welcome: "Välkommen till administrationspanelen!",
    title_welcome: "Välkommen",
    error_generic: "Ett fel har inträffat.",
    success: "Framgång!",
    company_updated: "Företaget uppdaterades framgångsrikt.",
    company_saved_successfully: "Företagsuppgifterna sparades framgångsrikt.",
    zapisz: "Spara",
    anuluj: "Avbryt",
    // menu okna zarzadzaj firmami
    menu_label_zarzadzaj_firmami: "Bläddra bland företag",
    menu_otworz: "Bläddra bland företag",
    menu_zapisz: "Lägg till nytt företag",
    menu_edytuj: "Redigera företag",
    menu_usun: "Ta bort företag",
    menu_label_zarzadzaj_pracownikami: "Hantera anställda",
    menu_otworz_pracownikow: "Bläddra bland anställda",
    // alerty i komunikaty
    alert: "Varning!",
    confirm_cancel_edit: "Avbryta redigeringen?",
    confirm_delete_title: "Bekräftelse av borttagning",
    confirm_delete_message: "Är du säker på att du vill ta bort detta företag?",
    brak_dostempu_do_modulu: "Ingen åtkomst till modulen. Kontakta administratören.",
    usunieto_firme: "Företaget har tagits bort.",
    blad_przy_usuwaniu_firmy: "Ett fel uppstod vid borttagningen av företaget.",
    // content dla przegladania firm w formie tabeli
    lista_firm: "Företagslista",
    name: "Företagsnamn",
    type: "Företagstyp",
    active: "Aktiv",
    tax_id: "Skatte-ID",
    regon: "REGON",
    krs: "KRS",
    address: "Adress",
    city: "Stad",
    postal_code: "Postnummer",
    country: "Land",
    phone: "Telefon",
    email: "E-post",
    website: "Webbplats",
    validation_required: "Fältet {field} är obligatoriskt.",
    validation_max_length: "Fältet {field} kan innehålla högst {max} tecken.",
    validation_invalid_email: "Fältet {field} måste innehålla en giltig e-postadress.",
    validation_invalid_website: "Fältet {field} måste innehålla en giltig URL (http:// eller https://).",
    created_at: "Skapad den",
    updated_at: "Uppdaterad den",
    company_details: "Företagsinformation",
    users_list: "Företagsanvändare",
    user_name: "Namn",
    user_email: "E-post",
    user_role: "Roll",
    user_active: "Aktiv",
    user_lang: "Språk",
    no_users: "Inga användare hittades för detta företag."
  }
};

export default LAUNGE;
