const LAUNGE = {
  Polski: {
    icon: "🏬",
    label_zarzadzaj_firmami: "Zarządzaj firmami",
    welcome: "Witamy w panelu administracyjnym!",
    title_welcome: "Witamy",
    error_generic: "Wystąpił błąd.",
    zapisz: "Zapisz",
    anuluj: "Anuluj",
    // menu okna zarzadaj firmami
    menu_label_zarzadzaj_firmami: "Przeglądaj firmy",
    menu_otworz: "Przegladaj firmy",
    menu_zapisz: "Dodaj nową firmę",
    menu_edytuj: "Edytuj firmę",
    menu_usun: "Usuń firmę",
    // alerty i komunikaty
    alert: "Alert!",
    brak_dostempu_do_modulu: "Brak dostępu do modułu. Skontaktuj się z administratorem.",
    // content dla przegladania firm w formie tabeli
    lista_firm: "Lista firm",
    name: "Nazwa firmy",
    type: "Typ firmy",
    active: "Aktywna",
    tax_id: "NIP",
    regon: "REGON",
    krs: "KRS",
    address: "Adres",
    city: "Miasto",
    postal_code: "Kod pocztowy",
    country: "Kraj",
    phone: "Telefon",
    email: "Email",
    website: "Strona www",
    created_at: "Data utworzenia",
    updated_at: "Data aktualizacji",
    company_details: "Szczegóły firmy",
    users_list: "Użytkownicy firmy",
    user_name: "Imię",
    user_email: "Email",
    user_role: "Rola",
    user_active: "Aktywny",
    user_lang: "Język",
    no_users: "Brak użytkowników powiązanych z tą firmą."
  },

  English: {
    icon: "🏬",
    label_zarzadzaj_firmami: "Manage companies",
    welcome: "Welcome to the admin panel!",
    title_welcome: "Welcome",
    error_generic: "An error occurred.",
    zapisz: "Save",
    anuluj: "Cancel",
    // menu okna zarzadzaj firmami
    menu_label_zarzadzaj_firmami: "Browse companies",
    menu_otworz: "Browse companies",
    menu_zapisz: "Add new company",
    menu_edytuj: "Edit company",
    menu_usun: "Delete company",
    // alerty i komunikaty
    alert: "Alert!",
    brak_dostempu_do_modulu: "No access to the module. Please contact the administrator.",
    // content dla przegladania firm w formie tabeli
    lista_firm: "Company list",
    name: "Company Name",
    type: "Company Type",
    active: "Active",
    tax_id: "Tax ID",
    regon: "REGON",
    krs: "KRS",
    address: "Address",
    city: "City",
    postal_code: "Postal Code",
    country: "Country",
    phone: "Phone",
    email: "Email",
    website: "Website",
    created_at: "Created At",
    updated_at: "Updated At",
    company_details: "Company details",
    users_list: "Company users",
    user_name: "Name",
    user_email: "Email",
    user_role: "Role",
    user_active: "Active",
    user_lang: "Language",
    no_users: "No users found for this company."
  },

  Svenska: {
    icon: "🏬",
    label_zarzadzaj_firmami: "Hantera företag",
    welcome: "Välkommen till administrationspanelen!",
    title_welcome: "Välkommen",
    error_generic: "Ett fel har inträffat.",
    zapisz: "Spara",
    anuluj: "Avbryt",
    // menu okna zarzadzaj firmami
    menu_label_zarzadzaj_firmami: "Bläddra bland företag",
    menu_otworz: "Bläddra bland företag",
    menu_zapisz: "Lägg till nytt företag",
    menu_edytuj: "Redigera företag",
    menu_usun: "Ta bort företag",
    // alerty i komunikaty
    alert: "Varning!",
    brak_dostempu_do_modulu: "Ingen åtkomst till modulen. Kontakta administratören.",
    // content dla przegladania firm w formie tabeli
    lista_firm: "Företagslista",
    name: "Företagsnamn",
    type: "Företagstyp",
    active: "Aktiv",
    tax_id: "Skatte-ID",
    regon: "REGON",
    krs: "KRS",
    address: "Adress",
    city: "Stad",
    postal_code: "Postnummer",
    country: "Land",
    phone: "Telefon",
    email: "E-post",
    website: "Webbplats",
    created_at: "Skapad den",
    updated_at: "Uppdaterad den",
    company_details: "Företagsinformation",
    users_list: "Företagsanvändare",
    user_name: "Namn",
    user_email: "E-post",
    user_role: "Roll",
    user_active: "Aktiv",
    user_lang: "Språk",
    no_users: "Inga användare hittades för detta företag."
  }
};

export default LAUNGE;
